import { Country} from 'src/app/shared/models/Country.model';

export const countries: Country[] = [
  { code: 'AF', code3: 'AFG', name: 'Afghanistan', num: '004' },
  { code: "AL", code3: "ALB", name: "Albania", num: "008" },
  { code: "DZ", code3: "DZA", name: "Algeria", num: "012" },
  { code: "AS", code3: "ASM", name: "American Samoa", num: "016" },
  { code: "AD", code3: "AND", name: "Andorra", num: "020" },
  { code: "AO", code3: "AGO", name: "Angola", num: "024" },
  { code: "AI", code3: "AIA", name: "Anguilla", num: "660" },
  { code: "AQ", code3: "ATA", name: "Antarctica", num: "010" },
  { code: "AG", code3: "ATG", name: "Antigua and Barbuda", num: "028" },
  { code: "AR", code3: "ARG", name: "Argentina", num: "032" },
  { code: "AM", code3: "ARM", name: "Armenia", num: "051" },
  { code: "AW", code3: "ABW", name: "Aruba", num: "533" },
  { code: "AU", code3: "AUS", name: "Australia", num: "036" },
  { code: "AT", code3: "AUT", name: "Austria", num: "040" },
  { code: "AZ", code3: "AZE", name: "Azerbaijan", num: "031" },
  { code: "BS", code3: "BHS", name: "Bahamas (the)", num: "044" },
  { code: "BH", code3: "BHR", name: "Bahrain", num: "048" },
  { code: "BD", code3: "BGD", name: "Bangladesh", num: "050" },
  { code: "BB", code3: "BRB", name: "Barbados", num: "052" },
  { code: "BY", code3: "BLR", name: "Belarus", num: "112" },
  { code: "BE", code3: "BEL", name: "Belgium", num: "056" },
  { code: "BZ", code3: "BLZ", name: "Belize", num: "084" },
  { code: "BJ", code3: "BEN", name: "Benin", num: "204" },
  { code: "BM", code3: "BMU", name: "Bermuda", num: "060" },
  { code: "BT", code3: "BTN", name: "Bhutan", num: "064" },
  { code: "BO", code3: "BOL", name: "Bolivia (Plurinational State of)", num: "068" },
  { code: "BQ", code3: "BES", name: "Bonaire, Sint Eustatius and Saba", num: "535" },
  { code: "BA", code3: "BIH", name: "Bosnia and Herzegovina", num: "070" },
  { code: "BW", code3: "BWA", name: "Botswana", num: "072" },
  { code: "BV", code3: "BVT", name: "Bouvet Island", num: "074" },
  { code: "BR", code3: "BRA", name: "Brazil", num: "076" },
  { code: "IO", code3: "IOT", name: "British Indian Ocean Territory (the)", num: "086" },
  { code: "BN", code3: "BRN", name: "Brunei Darussalam", num: "096" },
  { code: "BG", code3: "BGR", name: "Bulgaria", num: "100" },
  { code: "BF", code3: "BFA", name: "Burkina Faso", num: "854" },
  { code: "BI", code3: "BDI", name: "Burundi", num: "108" },
  { code: "CV", code3: "CPV", name: "Cabo Verde", num: "132" },
  { code: "KH", code3: "KHM", name: "Cambodia", num: "116" },
  { code: "CM", code3: "CMR", name: "Cameroon", num: "120" },
  { code: "CA", code3: "CAN", name: "Canada", num: "124" },
  { code: "KY", code3: "CYM", name: "Cayman Islands (the)", num: "136" },
  { code: "CF", code3: "CAF", name: "Central African Republic (the)", num: "140" },
  { code: "TD", code3: "TCD", name: "Chad", num: "148" },
  { code: "CL", code3: "CHL", name: "Chile", num: "152" },
  { code: "CN", code3: "CHN", name: "China", num: "156" },
  { code: "CX", code3: "CXR", name: "Christmas Island", num: "162" },
  { code: "CC", code3: "CCK", name: "Cocos (Keeling) Islands (the)", num: "166" },
  { code: "CO", code3: "COL", name: "Colombia", num: "170" },
  { code: "KM", code3: "COM", name: "Comoros (the)", num: "174" },
  { code: "CD", code3: "COD", name: "Congo (the Democratic Republic of the)", num: "180" },
  { code: "CG", code3: "COG", name: "Congo (the)", num: "178" },
  { code: "CK", code3: "COK", name: "Cook Islands (the)", num: "184" },
  { code: "CR", code3: "CRI", name: "Costa Rica", num: "188" },
  { code: "HR", code3: "HRV", name: "Croatia", num: "191" },
  { code: "CU", code3: "CUB", name: "Cuba", num: "192" },
  { code: "CW", code3: "CUW", name: "Curaçao", num: "531" },
  { code: "CY", code3: "CYP", name: "Cyprus", num: "196" },
  { code: "CZ", code3: "CZE", name: "Czechia", num: "203" },
  { code: "CI", code3: "CIV", name: "Côte d'Ivoire", num: "384" },
  { code: "DK", code3: "DNK", name: "Denmark", num: "208" },
  { code: "DJ", code3: "DJI", name: "Djibouti", num: "262" },
  { code: "DM", code3: "DMA", name: "Dominica", num: "212" },
  { code: "DO", code3: "DOM", name: "Dominican Republic (the)", num: "214" },
  { code: "EC", code3: "ECU", name: "Ecuador", num: "218" },
  { code: "EG", code3: "EGY", name: "Egypt", num: "818" },
  { code: "SV", code3: "SLV", name: "El Salvador", num: "222" },
  { code: "GQ", code3: "GNQ", name: "Equatorial Guinea", num: "226" },
  { code: "ER", code3: "ERI", name: "Eritrea", num: "232" },
  { code: "EE", code3: "EST", name: "Estonia", num: "233" },
  { code: "SZ", code3: "SWZ", name: "Eswatini", num: "748" },
  { code: "ET", code3: "ETH", name: "Ethiopia", num: "231" },
  { code: "FK", code3: "FLK", name: "Falkland Islands (the) [Malvinas]", num: "238" },
  { code: "FO", code3: "FRO", name: "Faroe Islands (the)", num: "234" },
  { code: "FJ", code3: "FJI", name: "Fiji", num: "242" },
  { code: "FI", code3: "FIN", name: "Finland", num: "246" },
  { code: "FR", code3: "FRA", name: "France", num: "250" },
  { code: "GF", code3: "GUF", name: "French Guiana", num: "254" },
  { code: "PF", code3: "PYF", name: "French Polynesia", num: "258" },
  { code: "TF", code3: "ATF", name: "French Southern Territories (the)", num: "260" },
  { code: "GA", code3: "GAB", name: "Gabon", num: "266" },
  { code: "GM", code3: "GMB", name: "Gambia (the)", num: "270" },
  { code: "GE", code3: "GEO", name: "Georgia", num: "268" },
  { code: "DE", code3: "DEU", name: "Germany", num: "276" },
  { code: "GH", code3: "GHA", name: "Ghana", num: "288" },
  { code: "GI", code3: "GIB", name: "Gibraltar", num: "292" },
  { code: "GR", code3: "GRC", name: "Greece", num: "300" },
  { code: "GL", code3: "GRL", name: "Greenland", num: "304" },
  { code: "GD", code3: "GRD", name: "Grenada", num: "308" },
  { code: "GP", code3: "GLP", name: "Guadeloupe", num: "312" },
  { code: "GU", code3: "GUM", name: "Guam", num: "316" },
  { code: "GT", code3: "GTM", name: "Guatemala", num: "320" },
  { code: "GG", code3: "GGY", name: "Guernsey", num: "831" },
  { code: "GN", code3: "GIN", name: "Guinea", num: "324" },
  { code: "GW", code3: "GNB", name: "Guinea-Bissau", num: "624" },
  { code: "GY", code3: "GUY", name: "Guyana", num: "328" },
  { code: "HT", code3: "HTI", name: "Haiti", num: "332" },
  { code: "HM", code3: "HMD", name: "Heard Island and McDonald Islands", num: "334" },
  { code: "VA", code3: "VAT", name: "Holy See (the)", num: "336" },
  { code: "HN", code3: "HND", name: "Honduras", num: "340" },
  { code: "HK", code3: "HKG", name: "Hong Kong", num: "344" },
  { code: "HU", code3: "HUN", name: "Hungary", num: "348" },
  { code: "IS", code3: "ISL", name: "Iceland", num: "352" },
  { code: "IN", code3: "IND", name: "India", num: "356" },
  { code: "ID", code3: "IDN", name: "Indonesia", num: "360" },
  { code: "IR", code3: "IRN", name: "Iran (Islamic Republic of)", num: "364" },
  { code: "IQ", code3: "IRQ", name: "Iraq", num: "368" },
  { code: "IE", code3: "IRL", name: "Ireland", num: "372" },
  { code: "IM", code3: "IMN", name: "Isle of Man", num: "833" },
  { code: "IL", code3: "ISR", name: "Israel", num: "376" },
  { code: "IT", code3: "ITA", name: "Italy", num: "380" },
  { code: "JM", code3: "JAM", name: "Jamaica", num: "388" },
  { code: "JP", code3: "JPN", name: "Japan", num: "392" },
  { code: "JE", code3: "JEY", name: "Jersey", num: "832" },
  { code: "JO", code3: "JOR", name: "Jordan", num: "400" },
  { code: "KZ", code3: "KAZ", name: "Kazakhstan", num: "398" },
  { code: "KE", code3: "KEN", name: "Kenya", num: "404" },
  { code: "KI", code3: "KIR", name: "Kiribati", num: "296" },
  { code: "KP", code3: "PRK", name: "Korea (the Democratic People's Republic of)", num: "408" },
  { code: "KR", code3: "KOR", name: "Korea (the Republic of)", num: "410" },
  { code: "KW", code3: "KWT", name: "Kuwait", num: "414" },
  { code: "KG", code3: "KGZ", name: "Kyrgyzstan", num: "417" },
  { code: "LA", code3: "LAO", name: "Lao People's Democratic Republic (the)", num: "418" },
  { code: "LV", code3: "LVA", name: "Latvia", num: "428" },
  { code: "LB", code3: "LBN", name: "Lebanon", num: "422" },
  { code: "LS", code3: "LSO", name: "Lesotho", num: "426" },
  { code: "LR", code3: "LBR", name: "Liberia", num: "430" },
  { code: "LY", code3: "LBY", name: "Libya", num: "434" },
  { code: "LI", code3: "LIE", name: "Liechtenstein", num: "438" },
  { code: "LT", code3: "LTU", name: "Lithuania", num: "440" },
  { code: "LU", code3: "LUX", name: "Luxembourg", num: "442" },
  { code: "MO", code3: "MAC", name: "Macao", num: "446" },
  { code: "MG", code3: "MDG", name: "Madagascar", num: "450" },
  { code: "MW", code3: "MWI", name: "Malawi", num: "454" },
  { code: "MY", code3: "MYS", name: "Malaysia", num: "458" },
  { code: "MV", code3: "MDV", name: "Maldives", num: "462" },
  { code: "ML", code3: "MLI", name: "Mali", num: "466" },
  { code: "MT", code3: "MLT", name: "Malta", num: "470" },
  { code: "MH", code3: "MHL", name: "Marshall Islands (the)", num: "584" },
  { code: "MQ", code3: "MTQ", name: "Martinique", num: "474" },
  { code: "MR", code3: "MRT", name: "Mauritania", num: "478" },
  { code: "MU", code3: "MUS", name: "Mauritius", num: "480" },
  { code: "YT", code3: "MYT", name: "Mayotte", num: "175" },
  { code: "MX", code3: "MEX", name: "Mexico", num: "484" },
  { code: "FM", code3: "FSM", name: "Micronesia (Federated States of)", num: "583" },
  { code: "MD", code3: "MDA", name: "Moldova (the Republic of)", num: "498" },
  { code: "MC", code3: "MCO", name: "Monaco", num: "492" },
  { code: "MN", code3: "MNG", name: "Mongolia", num: "496" },
  { code: "ME", code3: "MNE", name: "Montenegro", num: "499" },
  { code: "MS", code3: "MSR", name: "Montserrat", num: "500" },
  { code: "MA", code3: "MAR", name: "Morocco", num: "504" },
  { code: 'MZ', code3: 'MOZ', name: "Mozambique", num: "508" },
  { code: "MM", code3: 'MMR', name: "Myanmar", num: "104" },
  { code: "NA", code3: "NAM", name: "Namibia", num: "516" },
  { code: "NR", code3: "NRU", name: "Nauru", num: "520" },
  { code: "NP", code3: "NPL", name: "Nepal", num: "524" },
  { code: "NL", code3: "NLD", name: "Netherlands (the)", num: "528" },
  { code: "NC", code3: "NCL", name: "New Caledonia", num: "540" },
  { code: "NZ", code3: "NZL", name: "New Zealand", num: "554" },
  { code: "NI", code3: "NIC", name: "Nicaragua", num: "558" },
  { code: "NE", code3: "NER", name: "Niger (the)", num: "562" },
  { code: "NG", code3: "NGA", name: "Nigeria", num: "566" },
  { code: "NU", code3: "NIU", name: "Niue", num: "570" },
  { code: "NF", code3: "NFK", name: "Norfolk Island", num: "574" },
  { code: "MP", code3: "MNP", name: "Northern Mariana Islands (the)", num: "580" },
  { code: "NO", code3: "NOR", name: "Norway", num: "578" },
  { code: "OM", code3: "OMN", name: "Oman", num: "512" },
  { code: "PK", code3: "PAK", name: "Pakistan", num: "586" },
  { code: "PW", code3: "PLW", name: "Palau", num: "585" },
  { code: "PS", code3: "PSE", name: "Palestine, State of", num: "275" },
  { code: "PA", code3: "PAN", name: "Panama", num: "591" },
  { code: "PG", code3: "PNG", name: "Papua New Guinea", num: "598" },
  { code: "PY", code3: "PRY", name: "Paraguay", num: "600" },
  { code: "PE", code3: "PER", name: "Peru", num: "604" },
  { code: "PH", code3: "PHL", name: "Philippines (the)", num: "608" },
  { code: "PN", code3: "PCN", name: "Pitcairn", num: "612" },
  { code: "PL", code3: "POL", name: "Poland", num: "616" },
  { code: "PT", code3: "PRT", name: "Portugal", num: "620" },
  { code: "PR", code3: "PRI", name: "Puerto Rico", num: "630" },
  { code: "QA", code3: "QAT", name: "Qatar", num: "634" },
  { code: "MK", code3: "MKD", name: "Republic of North Macedonia", num: "807" },
  { code: "RO", code3: "ROU", name: "Romania", num: "642" },
  { code: "RU", code3: "RUS", name: "Russian Federation (the)", num: "643" },
  { code: "RW", code3: "RWA", name: "Rwanda", num: "646" },
  { code: "RE", code3: "REU", name: "Réunion", num: "638" },
  { code: "BL", code3: "BLM", name: "Saint Barthélemy", num: "652" },
  { code: "SH", code3: "SHN", name: "Saint Helena, Ascension and Tristan da Cunha", num: "654" },
  { code: "KN", code3: "KNA", name: "Saint Kitts and Nevis", num: "659" },
  { code: "LC", code3: "LCA", name: "Saint Lucia", num: "662" },
  { code: "MF", code3: "MAF", name: "Saint Martin (French part)", num: "663" },
  { code: "PM", code3: "SPM", name: "Saint Pierre and Miquelon", num: "666" },
  { code: "VC", code3: "VCT", name: "Saint Vincent and the Grenadines", num: "670" },
  { code: "WS", code3: "WSM", name: "Samoa", num: "882" },
  { code: "SM", code3: "SMR", name: "San Marino", num: "674" },
  { code: "ST", code3: "STP", name: "Sao Tome and Principe", num: "678" },
  { code: "SA", code3: "SAU", name: "Saudi Arabia", num: "682" },
  { code: "SN", code3: "SEN", name: "Senegal", num: "686" },
  { code: "RS", code3: "SRB", name: "Serbia", num: "688" },
  { code: "SC", code3: "SYC", name: "Seychelles", num: "690" },
  { code: "SL", code3: "SLE", name: "Sierra Leone", num: "694" },
  { code: "SG", code3: "SGP", name: "Singapore", num: "702" },
  { code: "SX", code3: "SXM", name: "Sint Maarten (Dutch part)", num: "534" },
  { code: "SK", code3: "SVK", name: "Slovakia", num: "703" },
  { code: "SI", code3: "SVN", name: "Slovenia", num: "705" },
  { code: "SB", code3: "SLB", name: "Solomon Islands", num: "090" },
  { code: "SO", code3: "SOM", name: "Somalia", num: "706" },
  { code: "ZA", code3: "ZAF", name: "South Africa", num: "710" },
  { code: "GS", code3: "SGS", name: "South Georgia and the South Sandwich Islands", num: "239" },
  { code: "SS", code3: "SSD", name: "South Sudan", num: "728" },
  { code: "ES", code3: "ESP", name: "Spain", num: "724" },
  { code: "LK", code3: "LKA", name: "Sri Lanka", num: "144" },
  { code: "SD", code3: "SDN", name: "Sudan (the)", num: "729" },
  { code: "SR", code3: "SUR", name: "Suriname", num: "740" },
  { code: "SJ", code3: "SJM", name: "Svalbard and Jan Mayen", num: "744" },
  { code: "SE", code3: "SWE", name: "Sweden", num: "752" },
  { code: "CH", code3: "CHE", name: "Switzerland", num: "756" },
  { code: "SY", code3: "SYR", name: "Syrian Arab Republic", num: "760" },
  { code: "TW", code3: "TWN", name: "Taiwan", num: "158" },
  { code: "TJ", code3: "TJK", name: "Tajikistan", num: "762" },
  { code: "TZ", code3: "TZA", name: "Tanzania, United Republic of", num: "834" },
  { code: "TH", code3: "THA", name: "Thailand", num: "764" },
  { code: "TL", code3: "TLS", name: "Timor-Leste", num: "626" },
  { code: "TG", code3: "TGO", name: "Togo", num: "768" },
  { code: "TK", code3: "TKL", name: "Tokelau", num: "772" },
  { code: "TO", code3: "TON", name: "Tonga", num: "776" },
  { code: "TT", code3: "TTO", name: "Trinidad and Tobago", num: "780" },
  { code: "TN", code3: "TUN", name: "Tunisia", num: "788" },
  { code: "TR", code3: "TUR", name: "Turkey", num: "792" },
  { code: "TM", code3: "TKM", name: "Turkmenistan", num: "795" },
  { code: "TC", code3: "TCA", name: "Turks and Caicos Islands (the)", num: "796" },
  { code: "TV", code3: "TUV", name: "Tuvalu", num: "798" },
  { code: "UG", code3: "UGA", name: "Uganda", num: "800" },
  { code: "UA", code3: "UKR", name: "Ukraine", num: "804" },
  { code: "AE", code3: "ARE", name: "United Arab Emirates (the)", num: "784" },
  { code: "GB", code3: "GBR", name: "United Kingdom of Great Britain and Northern Ireland (the)", num: "826" },
  { code: "UM", code3: "UMI", name: "United States Minor Outlying Islands (the)", num: "581" },
  { code: "US", code3: "USA", name: "United States of America (the)", num: "840" },
  { code: "UY", code3: "URY", name: "Uruguay", num: "858" },
  { code: "UZ", code3: "UZB", name: "Uzbekistan", num: "860" },
  { code: "VU", code3: "VUT", name: "Vanuatu", num: "548" },
  { code: "VE", code3: "VEN", name: "Venezuela (Bolivarian Republic of)", num: "862" },
  { code: "VN", code3: "VNM", name: "Viet Nam", num: "704" },
  { code: "VG", code3: "VGB", name: "Virgin Islands (British)", num: "092" },
  { code: "VI", code3: "VIR", name: "Virgin Islands (U.S.)", num: "850" },
  { code: "WF", code3: "WLF", name: "Wallis and Futuna", num: "876" },
  { code: "EH", code3: "ESH", name: "Western Sahara", num: "732" },
  { code: "YE", code3: "YEM", name: "Yemen", num: "887" },
  { code: "ZM", code3: "ZMB", name: "Zambia", num: "894" },
  { code: "ZW", code3: "ZWE", name: "Zimbabwe", num: "716" },
  { code: "AX", code3: "ALA", name: "Åland Islands", num: "248" }
];
